name: Build everything
on:
  push:
    tags:
      - "v*"

jobs:
  linux-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build virtual mouse
        run: docker run -v "$PWD":/code saschpe/android-ndk:34-jdk22.0.1_8-ndk26.3.11579264-cmake3.22.1 bash /code/create-mouse
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mouse