name: Build everything
on:
  push:
    tags:
      - "v*"

jobs:
  linux-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build magsik patched boot
        run: bash ./create-boot
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            neutron-noavb.img
            neutron.img
